### ISSUE TITLE
The AoE 4 overlay does not update

### ISSUE THREAD

**Issue by MRT440** [FluffyMaguro/AoE4_Overlay#10]
Hello,

When you start a game and the AoE4 overlay is open. It doesn't refresh anymore. I have to restart the software for it to update. Do you have a solution for me please ?

**Comment by Stargate85** [comment]
I have the same problem since 1-2 weeks. I´m on the latest 1.4.0 release.

**Comment by FluffyMaguro** [comment]
Hey, could you try this version and see if there is any difference?
https://github.com/FluffyMaguro/AoE4_Overlay/releases/download/debug/AoE4_Overlay.zip

I wasn't able to replicate it, but perhaps this will help. You can also send me the log file.

**Comment by MRT440** [comment]
>
It works again with the link you sent! Thank you ! :)

**Comment by Stargate85** [comment]
I can confirm the same. For me it also works with the debug Version you shared. Thank you!

**Comment by FluffyMaguro** [comment]
Ok, thank you. I will push it as version 1.4.1
