### ISSUE TITLE
Overlay not displayed in-game

### ISSUE THREAD

**Issue by Eirikr211** [FluffyMaguro/AoE4_Overlay#11]
Hello! First of all thanks for the amazing job with this overlay, I wonder if you could help me. I on version 1.4.1. For some reasons the overlay runs correctly but is not showed ingame. Any ideas why it might be?

**Comment by CraftySalamander** [comment]
Hello. Which part of the overlay are you referring to?
The main panel (configuration, detailed stats) will not stay on top of your game while playing.
But, the 2 other panels (match data and build order) should stay on top of your game. You need to use the correct hotkeys to show them, see [here](https://youtu.be/R5t9P4-tMxg?t=176).

**Comment by FluffyMaguro** [comment]
Which overlay? Does it show in windows and not ingame?
If it shows in Windows, then try setting game's display setting to "borderless fullscreen".

**Comment by Eirikr211** [comment]
The problem was that at some point the hot keys to pop up the overlays were
the same for the build orders and for the details info. And when I changed
them to be different it did t work, I needed to restart de program.
