### ISSUE TITLE
Proposal to improve the list of build orders

### ISSUE THREAD

**Issue by qhorgues** [FluffyMaguro/AoE4_Overlay#12]
Add a check mark to hide a build order from rotation via the keyboard shortcut
And otherwise great project thanks to you

**Comment by CraftySalamander** [comment]
@qhorgues Thank you for the nice suggestion!

@FluffyMaguro I implemented the code change for this suggestion in Pull request #13 .
You can review it and merge it if it is fine for you.
Note that I added a new variable in settings.py. But, no variable name was changed, no variable was removed (in settings.py). So, it should not cause settings losses for the users.

**Comment by qhorgues** [comment]
Thanks to you
