### ISSUE TITLE
Question: How to modify the css properly?

### ISSUE THREAD

**Issue by jensbuehl** [FluffyMaguro/AoE4_Overlay#18]
Another one: In order to get to the same colors in the BO and Match-Overlay, I wanted to update some colors via “custom.css”. No matter what I add (same structure as main.css), the tool does not reflect the updated colors. Is there a trick to it? Could you maybe provide an example how to override at least colors or add it to the readme? :)

**Comment by FluffyMaguro** [comment]
No trick. To change visuals of streaming overlay (overlay.html), add stuff to custom.css
Use the same structures as main.css.

For changing colors, this is the baseline. Make sure it reloads the overlay. Using live reload in VSC works well.
```
#score {
    color: white;
}

#score #map {
    color: #29e0f8;
}

.player .name {
    color: #fff
}

.stats .rank {
    color: #ddd
}

.stats .rating {
    color: #7ab6ff
}

.stats .winrate {
    color: #fffb78
}

.stats .wins {
    color: #48bd21
}

.stats .losses {
    color: red
}
```

**Comment by jensbuehl** [comment]
I'll give it another try, thx.
Is it meant to be used for the streaming overlay only or also for the out-of-the-box overlay when playing the game?

**Comment by FluffyMaguro** [comment]
It's for streaming overlay only.

**Comment by jensbuehl** [comment]
Thx for clarifying! :)
