### ISSUE TITLE
Build Orders Not Saving

### ISSUE THREAD

**Issue by aniel987** [FluffyMaguro/AoE4_Overlay#3]
My build orders don't save when I close and reopen the app. I have to type them in again each time.

**Comment by FluffyMaguro** [comment]
Strange, send me the log file (File/log)

**Comment by aniel987** [comment]
Says the folder is empty

**Comment by FluffyMaguro** [comment]
Than it's likely a permission issue.
You can try adding an exception to your antivirus or change related OS settings.

**Comment by aniel987** [comment]
The app has all the correct permissions through antivirus and firewall. It worked previously but has stopped in the last update
